### PR TITLE
Add support for release specific variables and switch bionic to python3

### PR DESCRIPTION
**Pull request by litewhatever**
As discussed in https://github.com/kostiantyn-nemchenko/ansible-role-patroni/issues/70

### CODE REVIEW

**Comment by kostiantyn-nemchenko** [comment]
Thank you! I will try to take a look and test it on various platforms this week.

**Comment by litewhatever** [comment]
Makes sense.
I will revert changes, modify accordingly, test and push again.

**Comment by litewhatever** [comment]
And should be done.

**Comment by kostiantyn-nemchenko** [comment]
Merged, thank you @litewhatever !

**Pull request merged**
