### PR TITLE
Install EPEL for system packages

### PR DESCRIPTION
**Pull request by patsevanton**

### CODE REVIEW

**Comment by patsevanton** [comment]
Check on CentOS 7

**Comment by patsevanton** [comment]
Please review PR

**Comment by kostiantyn-nemchenko** [comment]
Actually, there is no need to define one more variable.
You should overwrite the [list of packages to install](https://github.com/kostiantyn-nemchenko/ansible-role-patroni/blob/dc3fa1cfebeb7293fd8bc7ff9a425574ceb9bbbd/defaults/main.yml#L10) using group_vars/host_vars/etc. concepts in Ansible.

**Comment by patsevanton** [comment]
python-pip have in EPEL repo.

**Pull request closed without merging**
